# Generated by Django 4.1.8 on 2024-10-08 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=100, null=True)),
                ('teneur_proteine', models.CharField(max_length=100, null=True)),
                ('prix_par_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('L', 'Litre')], default='g', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('temperature_courante', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('ref_bon', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('alimentation', 'Alimentation'), ('soin', 'Soins'), ('infrastructure', 'Infrastructure'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_depense', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EspecePoisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier_base64', models.TextField()),
                ('extension', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_introduction', models.DateField()),
                ('poids_initial', models.FloatField()),
                ('poids_actuel', models.FloatField()),
                ('nombre_alevins', models.IntegerField()),
                ('taux_mortalite', models.FloatField(default=0.0)),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.bassin')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.especepoisson')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bénéfice_cible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_mortalite', models.FloatField()),
                ('duree_elevage', models.IntegerField()),
                ('autres_depenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souche', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stade', models.CharField(max_length=100)),
                ('poids_min', models.IntegerField()),
                ('poids_max', models.IntegerField()),
                ('age_min', models.IntegerField(default=0)),
                ('age_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='superficie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.CharField(max_length=100)),
                ('capacite', models.FloatField()),
                ('unite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.IntegerField(default=0)),
                ('Poids', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_vente', models.DateField()),
                ('client', models.CharField(max_length=100)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('bon_de_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.bondecommande')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviCroissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField()),
                ('poids', models.FloatField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.FloatField(null=True)),
                ('date_mise_a_jour', models.DateField()),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.aliment')),
            ],
        ),
        migrations.CreateModel(
            name='RationAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(null=True)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_distrib', models.DateField()),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.aliment')),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
        migrations.CreateModel(
            name='NormeCroissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_min', models.FloatField()),
                ('poids_max', models.FloatField()),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.especepoisson')),
                ('stade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.stade')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.IntegerField(default=0)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_pisciculture.bondecommande')),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
        migrations.CreateModel(
            name='FichierDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='fichiers_depense/')),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='gestion_pisciculture.depense')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('date_vente', models.DateField()),
                ('quantite_vendue', models.FloatField(default=0)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nombre_jour', models.IntegerField(null=True)),
                ('status_actuel', models.CharField(choices=[('mauvaise', 'mauvaise'), ('moyenne', 'moyenne'), ('bonne', 'bonne')], max_length=20, null=True)),
                ('etat', models.BooleanField(default=0)),
                ('couleur', models.CharField(max_length=20, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
                ('stade_actuel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.stade')),
            ],
        ),
        migrations.AddField(
            model_name='especepoisson',
            name='souche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.souche'),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.client'),
        ),
        migrations.AddField(
            model_name='bassin',
            name='superficie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.superficie'),
        ),
        migrations.CreateModel(
            name='AlimentRecommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recommandee', models.FloatField()),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.aliment')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.especepoisson')),
                ('stade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.stade')),
            ],
        ),
    ]
