# Generated by Django 4.1.8 on 2024-10-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stade',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='age_min',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='poids_max',
        ),
        migrations.RemoveField(
            model_name='stade',
            name='poids_min',
        ),
    ]
