# Generated by Django 4.1.8 on 2024-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0002_remove_stade_age_max_remove_stade_age_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bassin',
            name='contenu_reel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bassin',
            name='ecart_contenu',
            field=models.FloatField(default=0),
        ),
    ]
