# Generated by Django 4.1.8 on 2024-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0003_bassin_contenu_reel_bassin_ecart_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='superficie',
            name='capacite_eau',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='superficie',
            name='profondeur',
            field=models.FloatField(default=0),
        ),
    ]
