# Generated by Django 4.1.8 on 2024-10-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0004_superficie_capacite_eau_superficie_profondeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bassin',
            name='capacite_eau_reel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bassin',
            name='ecart_capacite_eau',
            field=models.FloatField(default=0),
        ),
    ]
