# Generated by Django 4.1.8 on 2024-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0005_bassin_capacite_eau_reel_bassin_ecart_capacite_eau'),
    ]

    operations = [
        migrations.AddField(
            model_name='especepoisson',
            name='indice_conversion',
            field=models.FloatField(default=0),
        ),
    ]
