# Generated by Django 4.1.8 on 2024-11-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0007_mortalite_alimentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='poisson',
            name='nombre_poisson_dispo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poisson',
            name='taux_mortalite_reel',
            field=models.FloatField(default=0.0),
        ),
    ]
