# Generated by Django 4.1.8 on 2024-11-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0008_poisson_nombre_poisson_dispo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicroissance',
            name='poids_attendu_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='suivicroissance',
            name='poids_attendu_min',
            field=models.FloatField(default=0.0),
        ),
    ]
