# Generated by Django 4.1.8 on 2024-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0009_suivicroissance_poids_attendu_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_depense', models.DecimalField(decimal_places=2, default=1000000, help_text='Seuil total des dépenses pour déclencher une notification SMS.', max_digits=12)),
            ],
        ),
    ]
