# Generated by Django 4.1.8 on 2024-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0010_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='date_vente',
            field=models.DateField(null=True),
        ),
    ]
