# Generated by Django 4.1.8 on 2024-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0011_bondecommande_date_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='poids',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
