# Generated by Django 4.1.8 on 2024-11-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0012_alter_lignecommande_poids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sourcefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.BooleanField(default=0)),
                ('dateajout', models.DateField(auto_now_add=True)),
                ('datemotif', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historique_Sourcefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateajout', models.DateField(auto_now_add=True)),
                ('datemotif', models.DateField(auto_now=True)),
                ('sourcefine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.sourcefine')),
            ],
        ),
    ]
