# Generated by Django 4.1.8 on 2024-11-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0013_sourcefine_historique_sourcefine'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='sourcefine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.sourcefine'),
        ),
    ]
