# Generated by Django 4.1.8 on 2024-11-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0014_depense_sourcefine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_init', models.IntegerField()),
                ('quantite_transfere', models.IntegerField()),
                ('quantite_restante', models.IntegerField()),
                ('taux_mortalite', models.FloatField()),
                ('date_introduction', models.DateField()),
                ('date_fin_prevu', models.DateField()),
                ('date_fin_reel', models.DateField()),
                ('especepoisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.especepoisson')),
            ],
        ),
        migrations.AddField(
            model_name='poisson',
            name='bande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.bande'),
        ),
    ]
