# Generated by Django 4.1.8 on 2024-11-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0016_rename_taux_mortalite_bande_mortalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationalimentaire_recom', models.FloatField()),
                ('rationalimentaire_donnee', models.FloatField()),
                ('rationalimentaire_ecart', models.FloatField()),
                ('date_alimentation_auto', models.DateField(auto_now_add=True)),
                ('date_alimentation_reel', models.DateField(null=True)),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
    ]
