# Generated by Django 4.1.8 on 2024-11-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0017_suivialimentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivialimentaire',
            name='date_alimentation_auto',
            field=models.DateField(),
        ),
    ]
