# Generated by Django 4.1.8 on 2024-11-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0018_alter_suivialimentaire_date_alimentation_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivialimentaire',
            name='etapeevolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.etapeevolution'),
        ),
    ]
