# Generated by Django 4.1.8 on 2024-11-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0019_suivialimentaire_etapeevolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivialimentaire',
            name='etapeevolution',
        ),
        migrations.AddField(
            model_name='suivialimentaire',
            name='stade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.stade'),
        ),
    ]
