# Generated by Django 4.1.8 on 2024-11-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0021_remove_suivialimentaire_stade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nourrirpoisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationalimentaire_donnee', models.FloatField()),
                ('date_alimentation_reel', models.DateField()),
                ('etapeevolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.etapeevolution')),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
    ]
