# Generated by Django 4.1.8 on 2024-11-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0022_nourrirpoisson'),
    ]

    operations = [
        migrations.AddField(
            model_name='nourrirpoisson',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.aliment'),
        ),
    ]
