# Generated by Django 4.1.8 on 2024-11-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0023_nourrirpoisson_aliment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecheDeCalibrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_peche', models.DateField()),
                ('poids_moyen', models.FloatField()),
                ('quantite_peche', models.FloatField(default=0)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('poisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson')),
            ],
        ),
    ]
