# Generated by Django 4.1.8 on 2024-11-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0024_pechedecalibrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bande',
            name='quantite_disponible_vente',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='pechedecalibrage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.pechedecalibrage'),
        ),
    ]
