# Generated by Django 4.1.8 on 2024-11-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0025_bande_quantite_disponible_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='bande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.bande'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='poisson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.poisson'),
        ),
    ]
