# Generated by Django 4.1.8 on 2024-11-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0026_lignecommande_bande_alter_lignecommande_poisson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especepoisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.especepoisson')),
            ],
        ),
        migrations.CreateModel(
            name='demandeReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModeVente', models.CharField(choices=[('Bonchamp', 'Mode Bon Champ'), ('Livre', 'Mode Livraison')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('poids', models.FloatField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_reduction', models.FloatField()),
                ('prix_unitaire_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v1', models.BooleanField(default=False)),
                ('v2', models.BooleanField(default=False)),
                ('v3', models.BooleanField(default=False)),
                ('valide', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.client')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.especepoisson')),
            ],
        ),
    ]
