# Generated by Django 4.1.8 on 2024-11-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0027_modepaiement_modevente_demandereduction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
