# Generated by Django 4.1.8 on 2024-11-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0028_rename_client_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_solde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='reste_a_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.bondecommande')),
            ],
        ),
    ]
