# Generated by Django 4.1.8 on 2024-11-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pisciculture', '0029_vente_date_solde_vente_montant_paye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ajoute', models.FloatField()),
                ('date_mise_a_jour', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pisciculture.stockalimentaire')),
            ],
        ),
    ]
